Update deploy-pipelines.yml for Azure Pipelines

diff --git a/.devops/deploy-pipelines.yml b/.devops/deploy-pipelines.yml
--- a/.devops/deploy-pipelines.yml
+++ b/.devops/deploy-pipelines.yml
@@ -3,8 +3,8 @@
 variables:
   NAMESPACE: '$(TF_NAMESPACE)'
   DOCKER_IMAGE_NAME: '$(TF_DOCKER_IMAGE_NAME)'
-  CONTAINER_REGISTRY_NAME: '$(TF_CONTAINER_REGISTRY_NAME)'
-  CONTAINER_REGISTRY_SERVICE_CONN: '$(TF_CONTAINER_REGISTRY_SERVICE_CONN)'
+  CONTAINER_REGISTRY_NAME_PROD: '$(TF_CONTAINER_REGISTRY_NAME_PROD)'
+  CONTAINER_REGISTRY_SERVICE_CONN_PROD: '$(TF_CONTAINER_REGISTRY_SERVICE_CONN_PROD)'
   KUBERNETES_SERVICE_CONN_WEU_BETA: '$(TF_KUBERNETES_SERVICE_CONN_WEU_BETA)'
   KUBERNETES_SERVICE_CONN_WEU_PROD_01: '$(TF_KUBERNETES_SERVICE_CONN_WEU_PROD_01)'
   KUBERNETES_SERVICE_CONN_WEU_PROD_02: '$(TF_KUBERNETES_SERVICE_CONN_WEU_PROD_02)'
@@ -141,49 +141,49 @@ stages:
                   echo "We assume this reference to be a valid release: $(Build.SourceBranch). Therefore, there is no need to bundle a new release."
                 displayName: 'Skip release bundle'
 
-  # # Build
-  # - stage: Build
-  #   dependsOn: Release
-  #   jobs:
-  #     - job: 'Build'
-  #       steps:
-  #         - task: Docker@2
-  #           displayName: 'docker login'
-  #           inputs:
-  #             containerRegistry: 'io-p-payments-acr-docker-registry-prod'
-  #             command: 'login'
-  #         - task: Bash@3
-  #           displayName: 'docker build and push (force)'
-  #           condition: and(succeeded(), eq(${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}, True))
-  #           inputs:
-  #             targetType: 'inline'
-  #             script: |
-  #               echo "[INFO] the parameter FORCE_REPLACE_DOCKER_IMAGE is set to true, start build and push"
-  #               docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(Build.BuildId) .
-  #               docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(getpomversion.outputpomversion) .
-  #               docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest .
-  #               docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(Build.BuildId)
-  #               docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(getpomversion.outputpomversion)
-  #               docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest
-  #         - task: Bash@3
-  #           displayName: 'docker build and push'
-  #           condition: and(succeeded(), eq(${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}, False))
-  #           inputs:
-  #             targetType: 'inline'
-  #             script: |
-  #               # docker will return 0 on success or 1 on failure.
-  #               docker manifest inspect $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest > /dev/null
-  #               if [ $? -eq 0 ]; then
-  #                 echo "[INFO] docker image already exists in the registry, skip build and push"
-  #               else
-  #                 echo "[INFO] docker image does not exist in the registry, start build and push"
-  #                 docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(Build.BuildId) .
-  #                 docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(getpomversion.outputpomversion) .
-  #                 docker build -t $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest .
-  #                 docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(Build.BuildId)
-  #                 docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(getpomversion.outputpomversion)
-  #                 docker push $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):latest
-  #               fi
+  # Build
+  - stage: Build
+    dependsOn: Release
+    jobs:
+      - job: 'Build'
+        steps:
+          - task: Docker@2
+            displayName: 'docker login'
+            inputs:
+              containerRegistry: 'io-p-payments-acr-docker-registry-prod'
+              command: 'login'
+          - task: Bash@3
+            displayName: 'docker build and push (force)'
+            condition: and(succeeded(), eq(${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}, True))
+            inputs:
+              targetType: 'inline'
+              script: |
+                echo "[INFO] the parameter FORCE_REPLACE_DOCKER_IMAGE is set to true, start build and push"
+                docker build -t $(CONTAINER_REGISTRY_NAME_PROD)/$(DOCKER_IMAGE_NAME):$(Build.BuildId) .
+                docker build -t $(CONTAINER_REGISTRY_NAME_PROD)/$(DOCKER_IMAGE_NAME):$(nextversion.value) .
+                docker build -t $(CONTAINER_REGISTRY_NAME_PROD)/$(DOCKER_IMAGE_NAME):latest .
+                docker push $(CONTAINER_REGISTRY_NAME_PROD)/$(DOCKER_IMAGE_NAME):$(Build.BuildId)
+                docker push $(CONTAINER_REGISTRY_NAME_PROD)/$(DOCKER_IMAGE_NAME):$(nextversion.value)
+                docker push $(CONTAINER_REGISTRY_NAME_PROD)/$(DOCKER_IMAGE_NAME):latest
+          - task: Bash@3
+            displayName: 'docker build and push'
+            condition: and(succeeded(), eq(${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}, False))
+            inputs:
+              targetType: 'inline'
+              script: |
+                # docker will return 0 on success or 1 on failure.
+                docker manifest inspect $(CONTAINER_REGISTRY_NAME)/$(DOCKER_IMAGE_NAME):$(nextversion.value) > /dev/null
+                if [ $? -eq 0 ]; then
+                  echo "[INFO] docker image already exists in the registry, skip build and push"
+                else
+                  echo "[INFO] docker image does not exist in the registry, start build and push"
+                  docker build -t $(CONTAINER_REGISTRY_NAME_PROD)/$(DOCKER_IMAGE_NAME):$(Build.BuildId) .
+                  docker build -t $(CONTAINER_REGISTRY_NAME_PROD)/$(DOCKER_IMAGE_NAME):$(nextversion.value) .
+                  docker build -t $(CONTAINER_REGISTRY_NAME_PROD)/$(DOCKER_IMAGE_NAME):latest .
+                  docker push $(CONTAINER_REGISTRY_NAME_PROD)/$(DOCKER_IMAGE_NAME):$(Build.BuildId)
+                  docker push $(CONTAINER_REGISTRY_NAME_PROD)/$(DOCKER_IMAGE_NAME):$(nextversion.value)
+                  docker push $(CONTAINER_REGISTRY_NAME_PROD)/$(DOCKER_IMAGE_NAME):latest
+                fi
 
   # - stage: 'Serving_helm'
   #   displayName: 'Serving_Helm'
