add docker teamplate

diff --git a/.devops/deploy-pipelines.yml b/.devops/deploy-pipelines.yml
--- a/.devops/deploy-pipelines.yml
+++ b/.devops/deploy-pipelines.yml
@@ -63,7 +63,7 @@ resources:
     - repository: pagopaCommons
       type: github
       name: pagopa/azure-pipeline-templates
-      ref: add-deploy-release-decision
+      ref: add-docker-build
       endpoint: "azure-devops-github-ro-payments"
 
 pool:
@@ -117,43 +117,50 @@ stages:
               CURRENT_VERSION: $(current_version)
               CURRENT_VERSION_BRANCH: $(current_version_branch)
               CURRENT_VERSION_TAG: $(current_version_tag)
-              BUILD_ID: $(Build.BuildId)
+              BUILD_NUMBER: $(Build.BuildNumber)
               SOURCE_BRANCH_NAME: $(Build.SourceBranchName)
-          - task: Docker@2
-            displayName: "docker login"
-            inputs:
-              containerRegistry: "$(CONTAINER_REGISTRY_SERVICE_CONN_PROD)"
-              command: "login"
-          - task: Bash@3
-            displayName: "docker build and push (force)"
-            condition: and(succeeded(), eq(${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}, True))
-            inputs:
-              targetType: "inline"
-              script: |
-                echo "[INFO] the parameter FORCE_REPLACE_DOCKER_IMAGE is set to true, start build and push"
-                echo "[INFO] Image version: $(deploy_version_decision.value)"
-                docker build -t $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):$(deploy_version_decision.value) .
-                docker build -t $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):latest .
-                docker push $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):$(deploy_version_decision.value)
-                docker push $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):latest
-          - task: Bash@3
-            displayName: "docker build and push"
-            condition: and(succeeded(), eq(${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}, False))
-            inputs:
-              targetType: "inline"
-              script: |
-                # docker will return 0 on success or 1 on failure.
-                echo "[INFO] Image version: $(deploy_version_decision.value)"
-                docker manifest inspect $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):$(deploy_version_decision.value) > /dev/null
-                if [ $? -eq 0 ]; then
-                  echo "[INFO] docker image already exists in the registry, skip build and push"
-                else
-                  echo "[INFO] docker image does not exist in the registry, start build and push"
-                  docker build -t $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):$(deploy_version_decision.value) .
-                  docker build -t $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):latest .
-                  docker push $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):$(deploy_version_decision.value)
-                  docker push $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):latest
-                fi
+          - template: templates/docker-release/template.yaml@pagopaCommons
+            parameters:
+              CONTAINER_REGISTRY_SERVICE_CONN: $(CONTAINER_REGISTRY_SERVICE_CONN_PROD)
+              CONTAINER_REGISTRY_FQDN: $(CONTAINER_REGISTRY_FQDN_PROD)
+              DOCKER_IMAGE_NAME: $(DOCKER_IMAGE_NAME)
+              DOCKER_IMAGE_TAG: $(DOCKER_IMAGE_TAG)
+              FORCE_REPLACE_DOCKER_IMAGE: ${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}
+          # - task: Docker@2
+          #   displayName: "docker login"
+          #   inputs:
+          #     containerRegistry: "$(CONTAINER_REGISTRY_SERVICE_CONN_PROD)"
+          #     command: "login"
+          # - task: Bash@3
+          #   displayName: "docker build and push (force)"
+          #   condition: and(succeeded(), eq(${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}, True))
+          #   inputs:
+          #     targetType: "inline"
+          #     script: |
+          #       echo "[INFO] the parameter FORCE_REPLACE_DOCKER_IMAGE is set to true, start build and push"
+          #       echo "[INFO] Image version: $(deploy_version_decision.value)"
+          #       docker build -t $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):$(deploy_version_decision.value) .
+          #       docker build -t $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):latest .
+          #       docker push $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):$(deploy_version_decision.value)
+          #       docker push $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):latest
+          # - task: Bash@3
+          #   displayName: "docker build and push"
+          #   condition: and(succeeded(), eq(${{ parameters.FORCE_REPLACE_DOCKER_IMAGE }}, False))
+          #   inputs:
+          #     targetType: "inline"
+          #     script: |
+          #       # docker will return 0 on success or 1 on failure.
+          #       echo "[INFO] Image version: $(deploy_version_decision.value)"
+          #       docker manifest inspect $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):$(deploy_version_decision.value) > /dev/null
+          #       if [ $? -eq 0 ]; then
+          #         echo "[INFO] docker image already exists in the registry, skip build and push"
+          #       else
+          #         echo "[INFO] docker image does not exist in the registry, start build and push"
+          #         docker build -t $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):$(deploy_version_decision.value) .
+          #         docker build -t $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):latest .
+          #         docker push $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):$(deploy_version_decision.value)
+          #         docker push $(CONTAINER_REGISTRY_FQDN_PROD)/$(DOCKER_IMAGE_NAME):latest
+          #       fi
 
   # - stage: 'Serving_helm'
   #   displayName: 'Serving_Helm'
